### ISSUE TITLE
how do I remove the description (text) associated with the generated barcode, is there a tag to insert in the API?

### ISSUE THREAD

**Issue by developmentkw** [BarcodeAPI/server#14]
Hello, thank you for your great work, but I have a question, is it possible to remove the text associated with the barcode? thanks 

![image](https://github.com/BarcodeAPI/server/assets/112748267/45de17b1-a25f-4847-8537-854830193bb5)

**Comment by sacalito** [comment]
i also need this if possible please

**Comment by sacalito** [comment]
> i also need this if possible please

solved it temporarily using css

`
            <div style="height: 17px; overflow: hidden;">
                <img src="https://barcodeapi.org/api/128/{{$sale->id}}" style="width: 125px; height: 25px; display: block;">
            </div>
`

**Comment by MClarkDev** [comment]
I apologize for the delayed response, you can now use the render option: `?text=none`
